/**
 * useSmartGuides — alignment guide computation for visual drag/resize.
 *
 * Computes dynamic "smart guide" lines when a visual is being dragged or resized,
 * snapping to edges/centers of other visuals on the canvas (Power BI-style).
 *
 * Architecture:
 *   - Pure computation: takes candidate rects + moving rect, returns snapped position + active guides.
 *   - Stateless per call; the caller (useVisualDragResize) drives it on each pointer-move.
 *   - Guide state (activeGuides) is stored in a lightweight Zustand store so SmartGuideOverlay
 *     can subscribe without prop drilling through the visual tree.
 */

import { create } from 'zustand'

// ─── Types ────────────────────────────────────────────────────────────────────

/** Axis-aligned rectangle (canvas px). */
export interface Rect {
  x: number
  y: number
  w: number
  h: number
}

/** A single guide line to render on the overlay. */
export interface GuideLine {
  /** Horizontal = same Y across X span; Vertical = same X across Y span */
  orientation: 'horizontal' | 'vertical'
  /** Fixed coordinate (px) — the X for vertical, Y for horizontal */
  position: number
  /** Start of the span (px) */
  start: number
  /** End of the span (px) */
  end: number
}

/** Result of smart-guide snapping for one axis. */
interface AxisSnap {
  /** Snapped coordinate (same as input if no snap) */
  snapped: number
  /** Guide lines generated by this snap */
  guides: GuideLine[]
}

// ─── Lightweight guide-line store ─────────────────────────────────────────────

interface SmartGuideStore {
  activeGuides: GuideLine[]
  setActiveGuides: (guides: GuideLine[]) => void
  clearGuides: () => void
}

export const useSmartGuideStore = create<SmartGuideStore>((set) => ({
  activeGuides: [],
  setActiveGuides: (activeGuides) => set({ activeGuides }),
  clearGuides: () => set({ activeGuides: [] }),
}))

// ─── Core computation ─────────────────────────────────────────────────────────

/**
 * Given a moving rect and an array of other rects, compute axis-aligned snaps
 * and the guide lines to render.
 *
 * @param moving     The rect being dragged/resized (current raw position).
 * @param others     All other visual rects on the page (excludes the moving visual).
 * @param threshold  Maximum pixel distance for a snap to engage (default 5).
 * @returns          `{ snappedX, snappedY, guides }` — adjusted position + guide lines.
 */
export function computeSmartGuides(
  moving: Rect,
  others: Rect[],
  threshold: number = 5,
): { snappedX: number; snappedY: number; guides: GuideLine[] } {
  if (others.length === 0) {
    return { snappedX: moving.x, snappedY: moving.y, guides: [] }
  }

  const xSnap = snapAxis(
    'vertical',
    moving.x,
    moving.w,
    moving.y,
    moving.h,
    others,
    threshold,
  )

  const ySnap = snapAxis(
    'horizontal',
    moving.y,
    moving.h,
    moving.x,
    moving.w,
    others,
    threshold,
  )

  return {
    snappedX: xSnap.snapped,
    snappedY: ySnap.snapped,
    guides: [...xSnap.guides, ...ySnap.guides],
  }
}

/**
 * Snap one axis (X or Y). We check 3 edges of the moving rect against
 * 3 edges of each candidate rect:
 *   - leading edge  (left / top)
 *   - center
 *   - trailing edge (right / bottom)
 *
 * The closest match within threshold wins. Ties (multiple candidates at
 * the same distance) produce multiple guide lines.
 */
function snapAxis(
  guideOrientation: 'horizontal' | 'vertical',
  /** Moving rect: start position on *this* axis */
  pos: number,
  /** Moving rect: size on *this* axis */
  size: number,
  /** Moving rect: start on *cross* axis (for guide span) */
  crossPos: number,
  /** Moving rect: size on *cross* axis (for guide span) */
  crossSize: number,
  others: Rect[],
  threshold: number,
): AxisSnap {
  const movingLeading = pos
  const movingCenter = pos + size / 2
  const movingTrailing = pos + size

  // Each candidate match: which moving edge matched, at what target coordinate, and cross-axis span of the other rect
  interface Match {
    /** 'leading' | 'center' | 'trailing' — which edge of the moving rect snapped */
    edge: 'leading' | 'center' | 'trailing'
    /** The coordinate we'd snap to (on this axis) */
    target: number
    /** Absolute distance */
    dist: number
    /** Cross-axis info of the other rect (for guide span computation) */
    otherCrossStart: number
    otherCrossEnd: number
    /** Position on this axis of the other rect edge that generated the match */
    otherEdgePos: number
  }

  const allMatches: Match[] = []

  for (const other of others) {
    // Determine positions on this axis and cross axis
    const oPos = guideOrientation === 'vertical' ? other.x : other.y
    const oSize = guideOrientation === 'vertical' ? other.w : other.h
    const oCrossPos = guideOrientation === 'vertical' ? other.y : other.x
    const oCrossSize = guideOrientation === 'vertical' ? other.h : other.w

    const otherLeading = oPos
    const otherCenter = oPos + oSize / 2
    const otherTrailing = oPos + oSize

    const otherCrossStart = oCrossPos
    const otherCrossEnd = oCrossPos + oCrossSize

    // Check all 9 combinations (3 moving edges × 3 other edges)
    const edgePairs: Array<{ movingVal: number; otherVal: number; edge: Match['edge'] }> = [
      { movingVal: movingLeading, otherVal: otherLeading, edge: 'leading' },
      { movingVal: movingLeading, otherVal: otherTrailing, edge: 'leading' },
      { movingVal: movingTrailing, otherVal: otherLeading, edge: 'trailing' },
      { movingVal: movingTrailing, otherVal: otherTrailing, edge: 'trailing' },
      { movingVal: movingCenter, otherVal: otherCenter, edge: 'center' },
      // Also snap leading↔center and trailing↔center for more coverage
      { movingVal: movingLeading, otherVal: otherCenter, edge: 'leading' },
      { movingVal: movingTrailing, otherVal: otherCenter, edge: 'trailing' },
      { movingVal: movingCenter, otherVal: otherLeading, edge: 'center' },
      { movingVal: movingCenter, otherVal: otherTrailing, edge: 'center' },
    ]

    for (const { movingVal, otherVal, edge } of edgePairs) {
      const dist = Math.abs(movingVal - otherVal)
      if (dist <= threshold) {
        allMatches.push({
          edge,
          target: otherVal,
          dist,
          otherCrossStart,
          otherCrossEnd,
          otherEdgePos: otherVal,
        })
      }
    }
  }

  if (allMatches.length === 0) {
    return { snapped: pos, guides: [] }
  }

  // Pick the best (smallest distance). If multiple edges tie, prefer the one
  // that moves the rect the least.
  allMatches.sort((a, b) => a.dist - b.dist)
  const bestDist = allMatches[0].dist

  // Collect all matches at the best distance
  const bestMatches = allMatches.filter((m) => m.dist <= bestDist + 0.5)

  // Determine the snapped position from the first best match
  const best = bestMatches[0]
  let snapped: number
  switch (best.edge) {
    case 'leading':
      snapped = best.target
      break
    case 'center':
      snapped = best.target - size / 2
      break
    case 'trailing':
      snapped = best.target - size
      break
  }

  // Build guide lines for all matches at the snapped coordinate
  const guides: GuideLine[] = []
  const seenPositions = new Set<number>()

  for (const match of bestMatches) {
    // Deduplicate guide lines at the same position
    const guidePos = match.otherEdgePos
    if (seenPositions.has(guidePos)) continue
    seenPositions.add(guidePos)

    // The guide line spans from the min cross-start to the max cross-end
    // of the moving rect and the matched other rect
    const spanStart = Math.min(crossPos, match.otherCrossStart)
    const spanEnd = Math.max(crossPos + crossSize, match.otherCrossEnd)

    guides.push({
      orientation: guideOrientation,
      position: guidePos,
      start: spanStart,
      end: spanEnd,
    })
  }

  return { snapped, guides }
}

/**
 * Build a Rect from a VisualInfo-like object. Handles both flat and layout fields.
 */
export function visualToRect(visual: {
  id?: string
  x?: number
  y?: number
  width?: number
  height?: number
  layout?: { x?: number; y?: number; w?: number; h?: number }
}): Rect {
  return {
    x: visual.layout?.x ?? visual.x ?? 0,
    y: visual.layout?.y ?? visual.y ?? 0,
    w: visual.layout?.w ?? visual.width ?? 200,
    h: visual.layout?.h ?? visual.height ?? 200,
  }
}
