from __future__ import annotations

from dataclasses import asdict, dataclass
from typing import Any, Iterable, Optional


C0_PRESERVED = "C0"
C1_PARSED = "C1"
C2_MAPPED = "C2"
C3_EXECUTABLE = "C3"


@dataclass(frozen=True)
class MFunctionMetadata:
    name: str
    category: str
    compatibility_level: str
    execution: str
    notes: str = ""

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


def _fn(
    name: str,
    category: str,
    compatibility_level: str,
    execution: str,
    notes: str = "",
) -> MFunctionMetadata:
    return MFunctionMetadata(
        name=name,
        category=category,
        compatibility_level=compatibility_level,
        execution=execution,
        notes=notes,
    )


_SOURCE_FUNCTIONS = {
    "Access.Database": "access",
    "ActiveDirectory.Domains": "active_directory",
    "AdobeAnalytics.Cubes": "adobe_analytics",
    "AdoDotNet.DataSource": "ado_dotnet",
    "AnalysisServices.Databases": "analysis_services",
    "AzureStorage.BlobContents": "azure_blob",
    "AzureStorage.Blobs": "azure_blob",
    "AzureStorage.DataLake": "azure_data_lake",
    "AzureStorage.DataLakeContents": "azure_data_lake",
    "AzureStorage.Tables": "azure_table_storage",
    "Cdm.Contents": "cdm",
    "DB2.Database": "db2",
    "DeltaLake.Metadata": "delta_lake",
    "DeltaLake.Table": "delta_lake",
    "Essbase.Cubes": "essbase",
    "Excel.CurrentWorkbook": "excel_current_workbook",
    "Exchange.Contents": "exchange",
    "GoogleAnalytics.Accounts": "google_analytics",
    "Hdfs.Contents": "hdfs",
    "Hdfs.Files": "hdfs",
    "HdInsight.Containers": "hdinsight",
    "HdInsight.Contents": "hdinsight",
    "HdInsight.Files": "hdinsight",
    "Informix.Database": "informix",
    "MySQL.Database": "mysql",
    "OleDb.DataSource": "oledb",
    "Oracle.Database": "oracle",
    "Pdf.Tables": "pdf",
    "PostgreSQL.Database": "postgresql",
    "RData.FromBinary": "rdata",
    "Salesforce.Data": "salesforce",
    "Salesforce.Reports": "salesforce",
    "SapBusinessWarehouse.Cubes": "sap_business_warehouse",
    "SapHana.Database": "sap_hana",
    "SharePoint.Contents": "sharepoint",
    "Soda.Feed": "soda",
    "Sql.Databases": "sql",
    "Sybase.Database": "sybase",
    "Teradata.Database": "teradata",
    "Web.BrowserContents": "web",
    "Web.Page": "web",
    "WebAction.Request": "web_action",
    "File.Contents": "file",
    "Folder.Files": "folder",
    "Folder.Contents": "folder",
    "Csv.Document": "csv",
    "Excel.Workbook": "excel",
    "Json.Document": "json",
    "Xml.Tables": "xml",
    "Parquet.Document": "parquet",
    "Sql.Database": "sql",
    "Odbc.DataSource": "odbc",
    "OData.Feed": "odata",
    "Web.Contents": "web",
    "SharePoint.Files": "sharepoint",
    "SharePoint.Tables": "sharepoint",
}

_FOLDABLE_TABLE_FUNCTIONS = {
    "Table.SelectRows",
    "Table.SelectColumns",
    "Table.RemoveColumns",
    "Table.RenameColumns",
    "Table.DuplicateColumn",
    "Table.ReorderColumns",
    "Table.TransformColumnTypes",
    "Table.TransformColumns",
    "Table.TransformColumnNames",
    "Table.Distinct",
    "Table.Sort",
    "Table.FirstN",
    "Table.LastN",
    "Table.Skip",
    "Table.RemoveFirstN",
    "Table.RemoveLastN",
    "Table.Range",
    "Table.AddColumn",
    "Table.AddIndexColumn",
    "Table.Group",
    "Table.NestedJoin",
    "Table.Join",
    "Table.AggregateTableColumn",
    "Table.Combine",
    "Table.Pivot",
    "Table.Unpivot",
    "Table.UnpivotOtherColumns",
    "Table.ExpandTableColumn",
    "Table.ExpandRecordColumn",
    "Table.ExpandListColumn",
    "Table.ReplaceValue",
    "Table.ReplaceErrorValues",
    "Table.RemoveRowsWithErrors",
    "Table.SelectRowsWithErrors",
    "Table.FillDown",
    "Table.FillUp",
    "Table.PromoteHeaders",
    "Table.DemoteHeaders",
    "Table.SplitColumn",
    "Table.CombineColumns",
    "Table.ColumnNames",
    "Table.RowCount",
    "Table.FromRows",
    "Table.FromRecords",
    "Table.FromColumns",
    "Table.FromList",
    "Table.AddKey",
}

_CONSTRUCTOR_FUNCTIONS = {
    "#binary": "Binary constructor",
    "#table": "Table constructor",
    "#date": "Date constructor",
    "#datetime": "DateTime constructor",
    "#datetimezone": "DateTimeZone constructor",
    "#duration": "Duration constructor",
    "#time": "Time constructor",
}

_EVALUATOR_FUNCTIONS = {
    "AccessControlKind.Type",
    "BinaryEncoding.Type",
    "BinaryOccurrence.Type",
    "BufferMode.Type",
    "ByteOrder.Type",
    "Compression.Type",
    "CsvStyle.Type",
    "Culture.Current",
    "Day.Type",
    "ExtraValues.Type",
    "GroupKind.Type",
    "ItemExpression.Item",
    "ItemExpression.From",
    "JoinAlgorithm.Type",
    "JoinKind.Type",
    "JoinSide.Type",
    "LimitClauseKind.Type",
    "MissingField.Type",
    "Number.E",
    "Number.Epsilon",
    "Number.NaN",
    "Number.NegativeInfinity",
    "Number.PI",
    "Number.PositiveInfinity",
    "Occurrence.Type",
    "ODataOmitValues.Type",
    "Order.Type",
    "PercentileMode.Type",
    "Precision.Type",
    "QuoteStyle.Type",
    "RankKind.Type",
    "RelativePosition.Type",
    "RoundingMode.Type",
    "RowExpression.Row",
    "RowExpression.Column",
    "RowExpression.From",
    "SapBusinessWarehouseExecutionMode.Type",
    "SapHanaDistribution.Type",
    "SapHanaRangeOperator.Type",
    "TextEncoding.Type",
    "TimeZone.Current",
    "TraceLevel.Type",
    "WebMethod.Type",
    "List.Transform",
    "List.Select",
    "List.Accumulate",
    "List.Generate",
    "List.TransformMany",
    "List.Dates",
    "List.DateTimes",
    "List.DateTimeZones",
    "List.Durations",
    "List.Times",
    "List.Numbers",
    "List.Random",
    "List.ConformToPageReader",
    "List.Count",
    "List.NonNullCount",
    "List.Sum",
    "List.Product",
    "List.Min",
    "List.Max",
    "List.MinN",
    "List.MaxN",
    "List.Average",
    "List.Median",
    "List.Percentile",
    "List.Mode",
    "List.Modes",
    "List.StandardDeviation",
    "List.Variance",
    "List.Covariance",
    "List.Distinct",
    "List.Difference",
    "List.Intersect",
    "List.Union",
    "List.IsDistinct",
    "List.RemoveNulls",
    "List.Combine",
    "List.Zip",
    "List.IsEmpty",
    "List.Positions",
    "List.PositionOf",
    "List.PositionOfAny",
    "List.Buffer",
    "List.Reverse",
    "List.Sort",
    "List.Alternate",
    "List.FindText",
    "List.First",
    "List.Last",
    "List.Single",
    "List.SingleOrDefault",
    "List.FirstN",
    "List.LastN",
    "List.Range",
    "List.Skip",
    "List.RemoveFirstN",
    "List.RemoveLastN",
    "List.InsertRange",
    "List.RemoveRange",
    "List.ReplaceRange",
    "List.RemoveItems",
    "List.RemoveMatchingItems",
    "List.ReplaceMatchingItems",
    "List.ReplaceValue",
    "List.Repeat",
    "List.Split",
    "List.Contains",
    "List.ContainsAny",
    "List.ContainsAll",
    "List.MatchesAll",
    "List.MatchesAny",
    "List.AnyTrue",
    "List.AllTrue",
    "Table.Column",
    "Table.ApproximateRowCount",
    "Table.FirstValue",
    "Table.FromValue",
    "Table.HasColumns",
    "Table.IsDistinct",
    "Table.MatchesAllRows",
    "Table.MatchesAnyRows",
    "Table.PrefixColumns",
    "Table.SingleRow",
    "Table.Split",
    "Table.SplitAt",
    "Table.AddFuzzyClusterColumn",
    "Table.FilterWithDataTable",
    "Table.FuzzyGroup",
    "Table.FuzzyJoin",
    "Table.FuzzyNestedJoin",
    "Table.AddJoinColumn",
    "Table.AddRankColumn",
    "Table.CombineColumnsToRecord",
    "Table.FromPartitions",
    "Table.Partition",
    "Tables.GetRelationships",
    "Table.Keys",
    "Table.ReplaceKeys",
    "Table.PartionKey",
    "Table.ReplacePartitionKey",
    "Table.ReplaceRelationshipIdentity",
    "Table.PartitionValues",
    "Table.ConformToPageReader",
    "Table.WithErrorContext",
    "Table.ColumnCount",
    "Table.ColumnsOfType",
    "Table.Schema",
    "Table.Profile",
    "Table.IsEmpty",
    "Table.Sort",
    "Table.FindText",
    "Table.Contains",
    "Table.ContainsAny",
    "Table.ContainsAll",
    "Table.PositionOf",
    "Table.PositionOfAny",
    "Table.First",
    "Table.Last",
    "Table.Min",
    "Table.Max",
    "Table.MinN",
    "Table.MaxN",
    "Table.RemoveRows",
    "Table.RemoveMatchingRows",
    "Table.AlternateRows",
    "Table.ReplaceRows",
    "Table.ReplaceMatchingRows",
    "Table.InsertRows",
    "Table.ReverseRows",
    "Table.TransformRows",
    "Table.ToRecords",
    "Table.ToRows",
    "Table.ToColumns",
    "Table.ToList",
    "Table.Repeat",
    "Table.Transpose",
    "Table.TransformColumnNames",
    "Table.View",
    "AccessControlEntry.ConditionToIdentities",
    "Record.Field",
    "Record.FieldOrDefault",
    "Record.HasFields",
    "Record.FieldCount",
    "Record.FieldNames",
    "Record.FieldValues",
    "Record.ToList",
    "Record.Combine",
    "Record.AddField",
    "Record.FromList",
    "Record.FromTable",
    "Record.ToTable",
    "Record.SelectFields",
    "Record.RemoveFields",
    "Record.RenameFields",
    "Record.ReorderFields",
    "Record.TransformFieldNames",
    "Record.TransformFields",
    "Geography.FromWellKnownText",
    "Geography.ToWellKnownText",
    "GeographyPoint.From",
    "Geometry.FromWellKnownText",
    "Geometry.ToWellKnownText",
    "GeometryPoint.From",
    "Diagnostics.ActivityId",
    "Diagnostics.CorrelationId",
    "Diagnostics.Trace",
    "Character.FromNumber",
    "Character.ToNumber",
    "Lines.FromText",
    "Lines.ToText",
    "Lines.FromBinary",
    "Lines.ToBinary",
    "Uri.EscapeDataString",
    "Uri.UnescapeDataString",
    "Uri.Parts",
    "Uri.BuildQueryString",
    "Uri.Combine",
    "Comparer.Equals",
    "Comparer.FromCulture",
    "Comparer.Ordinal",
    "Comparer.OrdinalIgnoreCase",
    "Replacer.ReplaceText",
    "Replacer.ReplaceValue",
    "Splitter.SplitByNothing",
    "Splitter.SplitTextByAnyDelimiter",
    "Splitter.SplitTextByCharacterTransition",
    "Splitter.SplitTextByDelimiter",
    "Splitter.SplitTextByEachDelimiter",
    "Splitter.SplitTextByLengths",
    "Splitter.SplitTextByPositions",
    "Splitter.SplitTextByRanges",
    "Splitter.SplitTextByRepeatedLengths",
    "Splitter.SplitTextByWhitespace",
    "Combiner.CombineTextByEachDelimiter",
    "Combiner.CombineTextByDelimiter",
    "Combiner.CombineTextByLengths",
    "Combiner.CombineTextByPositions",
    "Combiner.CombineTextByRanges",
    "Binary.Buffer",
    "Binary.View",
    "Binary.InferContentType",
    "Binary.ApproximateLength",
    "Binary.Combine",
    "Binary.Compress",
    "Binary.From",
    "Binary.FromList",
    "Binary.FromText",
    "Binary.Range",
    "Binary.Split",
    "Binary.ToText",
    "Binary.ToList",
    "Binary.Length",
    "Binary.Decompress",
    "Binary.ViewError",
    "Binary.ViewFunction",
    "BinaryFormat.7BitEncodedSignedInteger",
    "BinaryFormat.7BitEncodedUnsignedInteger",
    "BinaryFormat.Binary",
    "BinaryFormat.Byte",
    "BinaryFormat.ByteOrder",
    "BinaryFormat.Choice",
    "BinaryFormat.Decimal",
    "BinaryFormat.Double",
    "BinaryFormat.Group",
    "BinaryFormat.Length",
    "BinaryFormat.List",
    "BinaryFormat.Null",
    "BinaryFormat.Record",
    "BinaryFormat.SignedInteger16",
    "BinaryFormat.SignedInteger32",
    "BinaryFormat.SignedInteger64",
    "BinaryFormat.Single",
    "BinaryFormat.Text",
    "BinaryFormat.Transform",
    "BinaryFormat.UnsignedInteger16",
    "BinaryFormat.UnsignedInteger32",
    "BinaryFormat.UnsignedInteger64",
    "Error.Record",
    "Expression.Constant",
    "Expression.Evaluate",
    "Expression.Identifier",
    "Function.From",
    "Function.Invoke",
    "Function.InvokeAfter",
    "Function.InvokeWithErrorContext",
    "Function.IsDataSource",
    "Function.ScalarVector",
    "Xml.Tables",
    "Text.Trim",
    "Text.TrimStart",
    "Text.TrimEnd",
    "Text.Clean",
    "Text.Upper",
    "Text.Lower",
    "Text.Proper",
    "Text.Contains",
    "Text.StartsWith",
    "Text.EndsWith",
    "Text.Length",
    "Text.Replace",
    "Text.PositionOf",
    "Text.PositionOfAny",
    "Text.Repeat",
    "Text.Insert",
    "Text.ReplaceRange",
    "Text.RemoveRange",
    "Text.Select",
    "Text.Remove",
    "Text.ToList",
    "Text.Reverse",
    "Text.Split",
    "Text.SplitAny",
    "Text.Combine",
    "Text.BeforeDelimiter",
    "Text.AfterDelimiter",
    "Text.BetweenDelimiters",
    "Text.Start",
    "Text.End",
    "Text.At",
    "Text.Middle",
    "Text.Range",
    "Text.PadStart",
    "Text.PadEnd",
    "Text.Format",
    "Text.From",
    "Guid.From",
    "Text.InferNumberType",
    "Text.NewGuid",
    "Text.ToBinary",
    "Text.FromBinary",
    "Number.From",
    "Number.FromText",
    "Number.ToText",
    "Number.Random",
    "Number.RandomBetween",
    "Byte.From",
    "Int8.From",
    "Int16.From",
    "Int32.From",
    "Int64.From",
    "Currency.From",
    "Decimal.From",
    "Double.From",
    "Single.From",
    "Percentage.From",
    "Number.Round",
    "Number.Abs",
    "Number.Sign",
    "Number.RoundUp",
    "Number.RoundDown",
    "Number.RoundTowardZero",
    "Number.RoundAwayFromZero",
    "Number.IsEven",
    "Number.IsOdd",
    "Number.Mod",
    "Number.Power",
    "Number.Sqrt",
    "Number.Exp",
    "Number.Ln",
    "Number.Log",
    "Number.Log10",
    "Number.Sin",
    "Number.Cos",
    "Number.Tan",
    "Number.Asin",
    "Number.Acos",
    "Number.Atan",
    "Number.Atan2",
    "Number.Sinh",
    "Number.Cosh",
    "Number.Tanh",
    "Number.Factorial",
    "Number.Combinations",
    "Number.Permutations",
    "Number.IsNaN",
    "Number.IsInfinity",
    "Number.BitwiseAnd",
    "Number.BitwiseOr",
    "Number.BitwiseXor",
    "Number.BitwiseNot",
    "Number.BitwiseShiftLeft",
    "Number.BitwiseShiftRight",
    "Number.IntegerDivide",
    "Date.From",
    "Date.FromText",
    "Date.IsInCurrentDay",
    "Date.IsInCurrentMonth",
    "Date.IsInCurrentQuarter",
    "Date.IsInCurrentWeek",
    "Date.IsInCurrentYear",
    "Date.IsInNextDay",
    "Date.IsInNextMonth",
    "Date.IsInNextNDays",
    "Date.IsInNextNMonths",
    "Date.IsInNextNQuarters",
    "Date.IsInNextNWeeks",
    "Date.IsInNextNYears",
    "Date.IsInNextQuarter",
    "Date.IsInNextWeek",
    "Date.IsInNextYear",
    "Date.IsInPreviousDay",
    "Date.IsInPreviousMonth",
    "Date.IsInPreviousNDays",
    "Date.IsInPreviousNMonths",
    "Date.IsInPreviousNQuarters",
    "Date.IsInPreviousNWeeks",
    "Date.IsInPreviousNYears",
    "Date.IsInPreviousQuarter",
    "Date.IsInPreviousWeek",
    "Date.IsInPreviousYear",
    "Date.IsInYearToDate",
    "Date.Year",
    "Date.Month",
    "Date.Day",
    "Date.ToRecord",
    "Date.ToText",
    "Date.QuarterOfYear",
    "Date.DayOfWeek",
    "Date.DayOfWeekName",
    "Date.DayOfYear",
    "Date.WeekOfYear",
    "Date.WeekOfMonth",
    "Date.MonthName",
    "Date.AddDays",
    "Date.AddWeeks",
    "Date.AddMonths",
    "Date.AddQuarters",
    "Date.AddYears",
    "Date.DaysInMonth",
    "Date.IsLeapYear",
    "Date.StartOfDay",
    "Date.EndOfDay",
    "Date.StartOfWeek",
    "Date.EndOfWeek",
    "Date.StartOfMonth",
    "Date.EndOfMonth",
    "Date.StartOfQuarter",
    "Date.EndOfQuarter",
    "Date.StartOfYear",
    "Date.EndOfYear",
    "DateTime.From",
    "DateTime.FromText",
    "DateTime.FixedLocalNow",
    "DateTime.IsInCurrentHour",
    "DateTime.IsInCurrentMinute",
    "DateTime.IsInCurrentSecond",
    "DateTime.IsInNextHour",
    "DateTime.IsInNextMinute",
    "DateTime.IsInNextNHours",
    "DateTime.IsInNextNMinutes",
    "DateTime.IsInNextNSeconds",
    "DateTime.IsInNextSecond",
    "DateTime.IsInPreviousHour",
    "DateTime.IsInPreviousMinute",
    "DateTime.IsInPreviousNHours",
    "DateTime.IsInPreviousNMinutes",
    "DateTime.IsInPreviousNSeconds",
    "DateTime.IsInPreviousSecond",
    "DateTime.LocalNow",
    "DateTime.ToText",
    "DateTime.ToRecord",
    "DateTime.AddZone",
    "DateTime.FromFileTime",
    "DateTime.Date",
    "DateTime.Time",
    "Time.Hour",
    "Time.Minute",
    "Time.Second",
    "Time.From",
    "Time.FromText",
    "Time.ToText",
    "Time.ToRecord",
    "Time.StartOfHour",
    "Time.EndOfHour",
    "DateTimeZone.FromText",
    "DateTimeZone.FixedLocalNow",
    "DateTimeZone.FixedUtcNow",
    "DateTimeZone.LocalNow",
    "DateTimeZone.UtcNow",
    "DateTimeZone.ToText",
    "DateTimeZone.ToRecord",
    "DateTimeZone.FromFileTime",
    "DateTimeZone.SwitchZone",
    "DateTimeZone.RemoveZone",
    "DateTimeZone.ToUtc",
    "DateTimeZone.ToLocal",
    "DateTimeZone.ZoneHours",
    "DateTimeZone.ZoneMinutes",
    "Logical.From",
    "Logical.FromText",
    "Logical.ToText",
    "Value.Type",
    "Value.Is",
    "Value.Metadata",
    "Value.ReplaceMetadata",
    "Value.RemoveMetadata",
    "Value.Add",
    "Action.WithErrorContext",
    "DirectQueryCapabilities.From",
    "Embedded.Value",
    "Excel.ShapeTable",
    "Graph.Nodes",
    "Html.Table",
    "Identity.From",
    "Identity.IsMemberOf",
    "IdentityProvider.Default",
    "Json.FromValue",
    "Module.Versions",
    "Odbc.InferOptions",
    "Progress.DataSourceProgress",
    "SqlExpression.SchemaFrom",
    "SqlExpression.ToExpression",
    "Value.Alternates",
    "Value.As",
    "Value.Compare",
    "Value.Divide",
    "Value.Equals",
    "Value.Expression",
    "Value.Firewall",
    "Value.FromText",
    "Value.Lineage",
    "Value.Multiply",
    "Value.NullableEquals",
    "Value.Optimize",
    "Value.Subtract",
    "Value.Traits",
    "Value.VersionIdentity",
    "Value.Versions",
    "Value.ViewError",
    "Value.ViewFunction",
    "Variable.Value",
    "Variable.ValueOrDefault",
    "Type.Is",
    "Type.AddTableKey",
    "Type.ClosedRecord",
    "Type.Facets",
    "Type.ForFunction",
    "Type.ForRecord",
    "Type.FunctionParameters",
    "Type.FunctionRequiredParameters",
    "Type.FunctionReturn",
    "Type.IsNullable",
    "Type.IsOpenRecord",
    "Type.ListItem",
    "Type.NonNullable",
    "Type.OpenRecord",
    "Type.RecordFields",
    "Type.ReplaceFacets",
    "Type.ReplaceTableKeys",
    "Type.ReplaceTablePartitionKey",
    "Type.TableColumn",
    "Type.TableKeys",
    "Type.TablePartitionKey",
    "Type.TableRow",
    "Type.TableSchema",
    "Type.Union",
    "DateTimeZone.From",
    "Duration.From",
    "Duration.FromText",
    "Duration.ToRecord",
    "Duration.Days",
    "Duration.Hours",
    "Duration.Minutes",
    "Duration.Seconds",
    "Duration.TotalDays",
    "Duration.TotalHours",
    "Duration.TotalMinutes",
    "Duration.TotalSeconds",
    "Duration.ToText",
    "Table.Buffer",
    "Table.StopFolding",
    "Value.ReplaceType",
    "Web.Headers",
    "Xml.Document",
    "Table.ViewError",
    "Table.ViewFunction",
    "Value.NativeQuery",
}

_PRESERVE_ONLY_FUNCTIONS = {
    "Cube.ApplyParameter",
    "Cube.AttributeMemberId",
    "Cube.AttributeMemberProperty",
    "Cube.CollapseAndRemoveColumns",
    "Cube.Dimensions",
    "Cube.DisplayFolders",
    "Cube.MeasureProperties",
    "Cube.MeasureProperty",
    "Cube.Measures",
    "Cube.Parameters",
    "Cube.Properties",
    "Cube.PropertyKey",
    "Cube.ReplaceDimensions",
    "Cube.Transform",
    "Cube.AddAndExpandDimensionColumn",
    "Cube.AddMeasureColumn",
    "AnalysisServices.Database",
    "FabricAI.Prompt",
    "PowerBI.Dataflows",
}

_NATIVE_QUERY_FUNCTIONS = {
    "AdoDotNet.Query",
    "Odbc.Query",
    "OleDb.Query",
    "Value.NativeQuery",
}


FUNCTION_REGISTRY: dict[str, MFunctionMetadata] = {}

for name, source_type in _SOURCE_FUNCTIONS.items():
    FUNCTION_REGISTRY[name.upper()] = _fn(
        name,
        "Accessing data",
        C3_EXECUTABLE,
        "source_map",
        f"Maps to a Dummy BI source block for {source_type} sources and has fixture-backed adapter parity.",
    )

for name in _FOLDABLE_TABLE_FUNCTIONS:
    FUNCTION_REGISTRY[name.upper()] = _fn(
        name,
        "Table",
        C3_EXECUTABLE,
        "neutral_transform_ast",
        "Planned foldable transform; executed once transpiler/evaluator coverage exists.",
    )

for name, notes in _CONSTRUCTOR_FUNCTIONS.items():
    FUNCTION_REGISTRY[name.upper()] = _fn(
        name,
        "Literal constructor",
        C3_EXECUTABLE,
        "local_evaluator",
        notes,
    )

for name in _EVALUATOR_FUNCTIONS:
    category = name.split(".", 1)[0]
    FUNCTION_REGISTRY[name.upper()] = _fn(
        name,
        category,
        C3_EXECUTABLE,
        "local_evaluator",
        "Planned evaluator function; SQL pushdown depends on source/dialect support.",
    )

for name in _NATIVE_QUERY_FUNCTIONS:
    FUNCTION_REGISTRY[name.upper()] = _fn(
        name,
        "Value",
        C3_EXECUTABLE,
        "native_query_review",
        "Native SQL text is preserved and fixture-backed execution requires explicit approval, connector binding, safe parameters, and audit diagnostics.",
    )

for name in _PRESERVE_ONLY_FUNCTIONS:
    FUNCTION_REGISTRY[name.upper()] = _fn(
        name,
        "Semantic source",
        C3_EXECUTABLE,
        "preserve_only",
        "Preserved for raw-M fidelity and executed through deterministic semantic/cube fixture adapters.",
    )


def get_function_metadata(name: str) -> Optional[MFunctionMetadata]:
    return FUNCTION_REGISTRY.get(str(name).strip().upper())


def list_function_metadata() -> list[MFunctionMetadata]:
    return sorted(FUNCTION_REGISTRY.values(), key=lambda item: item.name.upper())


def classify_function_names(functions: Iterable[str]) -> dict[str, dict[str, Any]]:
    out: dict[str, dict[str, Any]] = {}
    for fn in sorted({str(f).strip() for f in functions if str(f).strip()}, key=str.upper):
        meta = get_function_metadata(fn)
        if meta is None:
            out[fn] = {
                "name": fn,
                "category": "unknown",
                "compatibility_level": C0_PRESERVED,
                "execution": "unsupported",
                "notes": "Function is preserved in raw M but has no Dummy BI mapping yet.",
            }
        else:
            out[fn] = meta.to_dict()
    return out
